M48
; DRILL file {KiCad 7.0.9} date 2023-11-12T20:37:13 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-12T20:37:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X128.775Y-120.2
X130.043Y-122.919
T2
X92.583Y-38.735
T0
M30
